spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolmanagement
    username: root
    password: Ben@24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

logging: # Add this section
  level: # Indent under logging
    org.springframework.security: DEBUG  # Indent under level
